### ISSUE TITLE
burpsuite 2022.5 导入会报错

### ISSUE THREAD

**Issue by 188150486** [F6JO/RouteVulScan#24]

**Comment by 188150486** [comment]
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getHttpService()" because "this.currentlyDisplayedItem" is null
	at burp.kid.I3(Unknown Source)
	at burp.egi.getHttpService(Unknown Source)
	at burp.bdo.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:128)
	at burp.ezj.v(Unknown Source)
	at burp.gi.Y(Unknown Source)
	at burp.gyp.lambda$updateVisiblePanes$1(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at burp.me.S(Unknown Source)
	at burp.me.P(Unknown Source)
	at burp.gyp.Y(Unknown Source)
	at burp.gyp.r(Unknown Source)
	at burp.y57.K(Unknown Source)
	at burp.cda.B(Unknown Source)
	at burp.ws7.M(Unknown Source)
	at burp.y57.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addImpl(Container.java:1150)
	at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1015)
	at java.desktop/java.awt.Container.add(Container.java:1001)
	at java.desktop/javax.swing.JSplitPane.setLeftComponent(JSplitPane.java:459)
	at burp.y5k.p(Unknown Source)
	at burp.y5k.N(Unknown Source)
	at burp.y5k.S(Unknown Source)
	at burp.y5k.U(Unknown Source)
	at burp.y5k.S(Unknown Source)
	at burp.y5k.D(Unknown Source)
	at burp.y5k.lambda$new$0(Unknown Source)
	at burp.wll.layoutContainer(Unknown Source)
	at java.desktop/java.awt.Container.layout(Container.java:1541)
	at java.desktop/java.awt.Container.doLayout(Container.java:1530)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validate(Container.java:1660)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:757)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:755)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:754)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getHttpService()" because "this.currentlyDisplayedItem" is null
	at burp.kid.I3(Unknown Source)
	at burp.egi.getHttpService(Unknown Source)
	at burp.bdo.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:128)
	at burp.ezj.v(Unknown Source)
	at burp.gi.Y(Unknown Source)
	at burp.gyp.lambda$updateVisiblePanes$1(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at burp.me.S(Unknown Source)
	at burp.me.P(Unknown Source)
	at burp.gyp.Y(Unknown Source)
	at burp.gyp.r(Unknown Source)
	at burp.y57.K(Unknown Source)
	at burp.cda.B(Unknown Source)
	at burp.ws7.M(Unknown Source)
	at burp.y57.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addImpl(Container.java:1150)
	at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1015)
	at java.desktop/java.awt.Container.add(Container.java:1001)
	at java.desktop/javax.swing.JSplitPane.setLeftComponent(JSplitPane.java:459)
	at burp.y5k.p(Unknown Source)
	at burp.y5k.N(Unknown Source)
	at burp.y5k.S(Unknown Source)
	at burp.y5k.U(Unknown Source)
	at burp.y5k.S(Unknown Source)
	at burp.y5k.D(Unknown Source)
	at burp.y5k.lambda$new$0(Unknown Source)
	at burp.wll.layoutContainer(Unknown Source)
	at java.desktop/java.awt.Container.layout(Container.java:1541)
	at java.desktop/java.awt.Container.doLayout(Container.java:1530)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validate(Container.java:1660)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:757)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:755)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:754)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by 188150486** [comment]
自己编译会提示 没有pom文件 这个怎么搞

**Comment by 188150486** [comment]
师傅 麻烦看看这个是什么问题 导入会上面的错误 并且插件不会起作用

**Comment by 188150486** [comment]
MacbookPro :: Downloads/chrome_download/RouteVulScan-RouteVulScan1.4 » gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/leeyu/Downloads/chrome_download/RouteVulScan-RouteVulScan1.4/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'RouteVulScan-RouteVulScan1.4'.
> Could not find method compile() for arguments [net.portswigger.burp.extender:burp-extender-api:1.7.13] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by F6JO** [comment]
试试把插件的配置文件删掉试试，编译的话用gradle然后导入'com.github.johnrengelman.shadow' 用shadow插件打包
