### ISSUE TITLE
jdk1.8- zip END header not found

### ISSUE THREAD

**Issue by wxi3** [F6JO/RouteVulScan#45]

**Comment by wxi3** [comment]
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1483)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1491)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1329)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1292)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:710)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:345)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:316)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:255)
	at burp.Zuea.Zn(Unknown Source)
	at burp.Zuea.Zk(Unknown Source)
	at burp.Zu2b.ZK(Unknown Source)
	at burp.Zhsy.Zz(Unknown Source)
	at burp.Zxkk.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

目前是抱这个错误，尝试自己编译时，报下面这个错：
java.lang.Exception: Extension class is not a recognized type
	at burp.Zuea.Zn(Unknown Source)
	at burp.Zuea.Zk(Unknown Source)
	at burp.Zu2b.ZK(Unknown Source)
	at burp.Zhsy.Zz(Unknown Source)
	at burp.Zxkk.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
