### ISSUE TITLE
长时间使用会导致线程累加超过限制

### ISSUE THREAD

**Issue by kingz40o** [F6JO/RouteVulScan#5]
长时间使用会导致线程累加超过限制，无法创建新的线程报错，burp也会卡，必须重启
报错如下：
`
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:803)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1343)
	at func.vulscan.<init>(vulscan.java:61)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:75)
	at burp.khp.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by F6JO** [comment]
> 长时间使用会导致线程累加超过限制，无法创建新的线程报错 报错如下： `java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached at java.base/java.lang.Thread.start0(Native Method) at java.base/java.lang.Thread.start(Thread.java:803) at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937) at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1343) at func.vulscan.<init>(vulscan.java:61) at burp.BurpExtender.doPassiveScan(BurpExtender.java:75) at burp.khp.run(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834)`

收到，有时间修复一下

**Comment by F6JO** [comment]
师傅，我搞了很久也没出现这个报错，可以描述一下什么情况出现的这个错误吗，比如报错时线程设置了多少，连续运行了多久，有没有使用右键发送到插件这个功能等

**Comment by kingz40o** [comment]
20个线程，大概30分钟就报错了，感觉像是新burp的问题（202205、2022051），我测试了旧版本的也没发现问题

F6JO ***@***.***> 于2022年6月21日周二 23:13写道：
