### ISSUE TITLE
安装报错-导出jar方式错误？

### ISSUE THREAD

**Issue by furuanruan** [F6JO/RouteVulScan#7]
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at burp.d3n.a(Unknown Source)
	at burp.d3n.<init>(Unknown Source)
	at burp.dxk.a(Unknown Source)
	at burp.hrt.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by F6JO** [comment]
没找到burp.BurpExtender类啊师傅，可以用我打包好的

**Comment by shuaxingzi** [comment]
最新版1.3打包好的还是报错啊。
java.lang.NullPointerException
	at java.base/java.util.Hashtable.containsKey(Hashtable.java:352)
	at burp.Bfunc.Get_Views(Bfunc.java:27)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at burp.h8l.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
![image](https://user-images.githubusercontent.com/44746140/196577283-ae1ec2cb-9292-4e52-b946-b05e461cf53b.png)

**Comment by shuaxingzi** [comment]
> 1.3的规则文件更新了，可以更新一下规则文件，在源码里有的 忠厚老实的阿岩 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "F6JO/RouteVulScan" ***@***.***&gt;; 发送时间:&nbsp;2022年10月19日(星期三) 上午9:43 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [F6JO/RouteVulScan] 安装报错-导出jar方式错误？ (Issue #7) 最新版1.3打包好的还是报错啊。 java.lang.NullPointerException at java.base/java.util.Hashtable.containsKey(Hashtable.java:352) at burp.Bfunc.Get_Views(Bfunc.java:27) at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:60) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:567) at burp.h8l.lambda$registerExtenderCallbacks$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:835) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好使
